### ISSUE TITLE
Please update FluidSynth v2.3.6

### ISSUE THREAD

**Issue by pedrolcl** [flathub/shared-modules#307]
https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.6

**Comment by bbhtt** [comment]
Do you want to send a PR?

**Comment by pedrolcl** [comment]
No. But consider this ticket as a remainder that v2.3.6 has been released on Aug 3rd, 2024. 

Let's see how much time it takes to Flathub compared to [other distributions](https://repology.org/project/fluidsynth/versions) that are also driven by volunteers.

**Comment by bbhtt** [comment]
Then this issue has no use.

**Comment by pedrolcl** [comment]
That is the attitude I was expecting. Bravo!

**Comment by bbhtt** [comment]
If you want to see something else, I suggest not posting a comment that implies volunteers are not doing enough for you.

**Comment by ranisalt** [comment]
@bbhtt sorry to intrude, but I don't think you need to respond with such tone here and in #299, a similar issue that @pedrolcl has in fact contributed. If you don't think it's useful, "do you want to do the work yourself? otherwise the complaint is useless" sounds completely wrong and pushes possible contributors away, it's better if we are friendly

@pedrolcl looking at the changelog from fluidsynth it doesn't seem like 2.3.6 has relevant enough bugfixes to warrant urgency. If you think this is important, it would help to indeed open a PR and explain how this affects your/others, updating just because there is a new version is counterproductive, and the nature of how packages are built it will not have effect until all applications that depend on this are also updated. As @bbhtt emphasized and you already know, this is updated by volunteers it's hard to prioritize, so additional context goes a long way
