### ISSUE TITLE
Investigate SDL12-compat in the future

### ISSUE THREAD

**Issue by TingPing** [flathub/shared-modules#53]
There is a compat library implementing SDL 1's API with SDL 2: https://hg.libsdl.org/sdl12-compat

This will be a great quality of life improvement for many applications such as gaining Wayland support. https://www.youtube.com/watch?v=3uVmUCuJpF4

So we should look into replacing SDL 1 here.

**Comment by Pixelnarium** [comment]
Tried it with Unreal Tournament 2004. Kinda works, strange mouse behavior in fullscreen (does not move everywhere sometimes), does not list any resolution in the settings, a lot of FIXME messages in the terminal. But if one does configure everything via the ini files the game itself works.

So maybe not replace SDL1 here but add it as an option.

Sidenote: flatpak-builder does not support Mercurial. So same problem as: https://github.com/flathub/shared-modules/issues/41

**Comment by Eonfge** [comment]
To have this as alternative to SDL1.2 would be nice. It might not work well with all applications but some older games might really benefit from this.

**Comment by Eonfge** [comment]
I've implemented SDL 1.2 Compat in the first package;
https://github.com/flathub/com.zandronum.Zandronum/pull/23

We should also look into a shared-module, but this is a nice start

**Comment by ssokolow** [comment]
> It might not work well with all applications but some older games might really benefit from this.

It's not guaranteed to be drop-in compatible, but the README lists a bunch of [configuration options](https://github.com/libsdl-org/sdl12-compat#configuration-options) for situations like "using GPU scaling rather than actual monitor resolution changing breaks rendering".

> We should also look into a shared-module, but this is a nice start

There is currently a `shared-modules/SDL/sdl12-compat.json` and I'm using it without issue for [net.sourceforge.tomatoes.IHaveNoTomatoes](https://flathub.org/apps/details/net.sourceforge.tomatoes.IHaveNoTomatoes).

**Comment by orowith2os** [comment]
Done in https://github.com/flathub/shared-modules/commit/1b470b7982aa820ab2c972c8242f860e83ab6971
