### ISSUE TITLE
Set up code owners for modules

### ISSUE THREAD

**Issue by TingPing** [flathub/shared-modules#85]
For details on what code owners is:

- https://github.blog/2017-07-06-introducing-code-owners/
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

As shared-modules grows and gets more security sensitive modules we should have maintainers for each module so there is somebody taking responsibility for what is here rather than it becoming a dumping ground.

(Brought up because of #84)

Proposal for maintainers (need volunteers):

- [ ] SDL
- [ ] cld2
- [x] dbus-glib (@TingPing)
- [ ] glew
- [ ] glu
- [x] gtk2 (@TingPing)
- [x] gudev (@Erick555)
- [x] intltool (@TingPing)
- [ ] lame
- [x] libappindicator (@TingPing) 
- [ ] libmad
- [x] libsecret (@Lctrs)
- [ ] lua
- [x] python (@bilelmoussaoui)
- [ ] pygame
- [ ] qt4
- [ ] smpeg
- [x] openjpeg (@bochecha)

Then in the future all new modules will require an owner to be added.

**Comment by Erick555** [comment]
I can take care of gudev and hope [it could go away at some point in future](https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/196).

**Comment by Lctrs** [comment]
As I proposed to introduce it, I can take care of `libsecret`.

**Comment by TingPing** [comment]
Merged though volunteers would still be appreciated for some modules.

**Comment by bilelmoussaoui** [comment]
I can take care of python2

**Comment by Lctrs** [comment]
The `CODEOWNERS` file is currently useless for a big majority of modules if we don't have write access to this repository.

See https://github.com/flathub/shared-modules/blob/master/CODEOWNERS with all the errors highlighted.

**Comment by bochecha** [comment]
Why is openjpeg an error ? It seems to be assigned to me, what's the problem ?

-- 
Bochecha

Le 6 juin 2022 12:29:43 GMT+02:00, Lctrs ***@***.***> a écrit :

**Comment by Lctrs** [comment]
@bochecha that's because you don't have write access to this repository, as neither of the users highlighted in red does. So when a PR is made for these modules, we don't get a notification for it and can't merge it.

**Comment by bochecha** [comment]
Ah right !

It's because I was eventually forced to change my github account from bochecha to mbridon, because having lost the 2FA I lost access to my account and the github support team was unable to help :-/

So I renamed it from my nickname to my real name.

So I have this new "mbridon" account now and I think I can push to it, can you edit that file to fix the maintainer ?

-- 
Mathieu Bridon / bochecha

Le 7 juin 2022 13:57:01 GMT+02:00, Lctrs ***@***.***> a écrit :
***@***.*** that's because you don't have write access to this repository, as neither of the users highlighted in red does. So when a PR is made for these modules, we don't get a notification for it and can't merge it.

**Comment by TingPing** [comment]
I've invited everybody to the repo.

@bochecha I updated your informatin too.

I'll close this issue since there isn't anything more actionable here really. If anybody wants to help maintain any module just let us know :)
